More Exception types
VirgilSecurity/virgil-e3kit-kotlin pull request #37
Opened 2019-10-02 16:47 UTC by BuddahLD

2019-10-03 13:30 UTC, cardoso submitted a review, later dismissed
Looks good 👍 👏

2019-10-04 08:38 UTC, SanjoDeundiak commented on ethree-common/src/main/java/com/virgilsecurity/android/common/EThreeCore.kt
> +                                                              "should call register() of " +
typo

2019-10-04 08:58 UTC, SanjoDeundiak requested changes

2019-10-04 08:58 UTC, SanjoDeundiak commented on ethree-common/src/main/java/com/virgilsecurity/android/common/EThreeCore.kt
> +                                                              "should call register() of " +
Typo

2020-01-15 12:55 UTC, closed without merging